version: '3.8'  #the version of docker
services:
  db_postgres:
    image: postgres:15     #the image and its version
    container_name: crypto_container  #name of the container
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${db_database} 
      
    ports:
      - "${db_port}:5432"

    volumes:
      - pg_data_safe:/var/lib/postgresql/data
    
    restart: always

volumes:
      pg_data_safe:
